name: Deploy
on:
  push:
    branches: [ live ]
jobs:
  full_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1
      - name: get yarn
        run: npm i yarn -g
      - name: grab libs
        run: yarn install
      - name: build
        run: npm run build
      - name: deploy
        run: aws s3 sync ./output/ s3://instagram-dl.axel669.net/ --delete
